In [1]:
import numpy as np
import pandas as pd
import json

In [7]:
import json
import pandas as pd

# Load JSON data from the file
with open('metadata.json', 'r') as json_file:
    data = json.load(json_file)

# Convert the 'videos' list to a DataFrame
df = pd.DataFrame(data['videos'])

# Display the DataFrame

In [8]:
df.head()

,video title,views,date,products
0,Why Scientists Are Puzzled By This Virus,"2,601,335 views",17 Sept 2024,N/A
1,We Need to Rethink Exercise (Updated Version),"2,603,124 views",12 Sept 2024,4 products

In [4]:
dataframe=pd.read_json('metadata.json')

In [4]:
pd.set_option('display.max_columns',None)

In [5]:
dataframe.head(50)

                                              videos
0  {'video title': 'Why Scientists Are Puzzled By...
1  {'video title': 'We Need to Rethink Exercise (...